### ISSUE TITLE
Postal is somehow missing headers on some received mails (and marking them as spam)

### ISSUE THREAD

**Issue by boindil** [postalserver/postal#1624]
## Describe the bug

Some mails are missing headers in the header tab, while they are present in the eml, that can be downloaded from postal. This is somehow even affecting the spam-check.

I believe, that this has something to do with the field X-Google-DKIM-Signature where somehow content seems to be missing / an out of place newline. Just dont know whether its something on googles side or on postals side.

## To Reproduce

Send a few mails to postal. We used gmail.

## Expected behaviour

Headers not missing, mail not marked as SPAM

## Screenshots
<img width="852" alt="postal-header-fail-3" src="https://user-images.githubusercontent.com/4290644/136224357-c2cbac1c-29bf-4d0d-8227-8d293ed08d51.png">
<img width="404" alt="postal-header-fail-2" src="https://user-images.githubusercontent.com/4290644/136224374-523e2af9-6d04-4cbe-bd9d-41b930bd0118.png">

![postal-header-fail](https://user-images.githubusercontent.com/4290644/136224581-b7858a08-a03b-4381-b330-4425976144ac.jpg)

## Environment details 

Postal 2.0.0

**Comment by Csardelacal** [comment]
Hey there,

I seem to be having the same issue, but with a slight twist. We started using Freshdesk for our support inbox and we started seeing a bunch of very weird emails coming in.

We have an address endpoint that we got from Freshdesk to redirect our email to. So far, this works flawlessly, except for emails from GMail (but not all of them). This is what arrives on the Freshdesk end:

![Screenshot from 2021-11-03 13-20-03](https://user-images.githubusercontent.com/1152823/140058925-a067af57-8cfe-4f86-9397-edda6b04319e.png)

When clicking on the sender I get `j4q0qp@psrp.ourdomain.com`. So I'm certain that the email got routed through Postal. And when I click on the message I get the raw payload for the message, which incidentally begins with:

```
X-Gm-Message-State: AOAM5337hJxJkHq5IcUajB3WbteNp12EcmEMiguppQLi6FG8jgz8TzgG
	mV7qPdAU7G1pHmteJhZ51EJG0gwtdX6Ef2H4PoVhoGMs1to=
X-Google-Smtp-Source: ABdhPJzdGihJNXK1xY62ruEfNmroF9bG64AHQSzGIXo4RusL4Ci0+VgLLmvl+6XXvB2aPvRD4m/jqAZsN1HvXFCB7xU=
X-Received: by 2002:a17:907:60c9:: with SMTP id hv9mr34603581ejc.334.1635940921262;
 Wed, 03 Nov 2021 05:02:01 -0700 (PDT)
MIME-Version: 1.0
From: <<removed>>
Date: Wed, 3 Nov 2021 07:01:46 -0500
Message-ID: <<<removed>>@mail.gmail.com>
```

The first (X-Gm-Message-State) is the header that @boindil has right after his broken header. On my Server the email does not appear among the incoming emails for the server. Is there anything I can do to help diagnose the issue?

Also notable: The psrp for ALL of these broken messages is the same address (j4q0qp).

**Comment by Wouter0100** [comment]
I found what is happening here: Postal is splitting the message in 2 raw parts: header and body. This is happening incorrectly, as it seems part of the header is in the body. I have had this happen to me as well just today. 

The new line in the initial issue (`X-Google-DKIM-Signature`) is from the fact that Postal adds a new line between the header and body, when stitching them back together. This breaks everything. 

In my case it's the `ARC-Message-Signature` header being split, and it is coming a Yahoo recipient. Although, we proxy all our e-mails through Google (as Google is running on our MX, we use Recipient Address Maps in Gmail to forward incoming e-mails to a Routing route's e-mail address in Postal).

One interesting thing I'm seeing is that it's always the last line of a multi-line header (at least, it's the case with me and with the person reporting the issue):
![image](https://user-images.githubusercontent.com/864520/189860007-9663b780-ad22-43b5-9a63-a23bcdbf848a.png)

Here the output of a MySQL query that shows the split in the 2 different rows within the `raw`-table (1162 is the raw body ID):
![image](https://user-images.githubusercontent.com/864520/189860347-dc6b84ce-eaa7-47a1-913b-868b19c9698d.png)

I had this on Postal 2.1.2.

@willpower232 do you have any idea? I don't see how [this](https://github.com/postalserver/postal/blob/2e7aaaba5a9a37f32bdff9a9fde0379834b2a4db/lib/postal/message_db/database.rb#L113) line could cause this, only if, due to an error, somehow elsewhere a new line is added within the header.

**Comment by Wouter0100** [comment]
Just to continue on the topic above, I'm unable to further investigate the issue rn. I have:
- Enabled SMTP data logging on this specific email server within Postal.
- Send a copy of each email to a seperate inbox before it is send to Postal.

With these 2 measures I'm hopefully able to see what emails will get stuck and determine their exact raw message before it reaches Postal.

**Comment by Wouter0100** [comment]
Interestingly enough it seem to start happening more and more often. Could be that we recently onboarded a customer with a lot more variation in their e-mailing, not sure.

Regardless, we already had a sample from which we received a copy e-mail. Right now it wasn't before the end of a multi-line header and it was in the `X-SONIC-DKIM-SIGN` header. So it seems.. right. Random.

Left the one copy we received on another server, right how Postal spits out the body+header. This means that no lines are missing or so.
![image](https://user-images.githubusercontent.com/864520/189919659-4e7af653-9783-4aec-bea5-2e176de6067d.png)

**Comment by Wouter0100** [comment]
I was able to reproduce it with my own emailing. Let's get debugging! 

Right.. I found that the new line happens in between 2 buffers and the new line happens on the beginning of a new buffer. Could it be that the buffer is ending in between a `\r\n`, which causes a new line twice because of [this normalize step](https://github.com/postalserver/postal/blob/6bace2c9053e8bdfc2689c3c92a9fc066d124401/lib/postal/smtp_server/server.rb#L152)? One `\r` in the ending buffer, and one `\n` in the new buffer.

This peace of ruby:
```ruby
test = "--\r--".encode("BINARY", universal_newline: true).encode("BINARY", crlf_newline: true)
test1 = "--\n--".encode("BINARY", universal_newline: true).encode("BINARY", crlf_newline: true)
puts "Hello, ==#{test}==#{test1}==!";
```
Results in:
```
Hello, ==--

--==--

--==!
```

So this could very well be the case, as in this case the new lines are thus handled twice. 

@willpower232 do you have an idea on how to solve this? It's a little more difficult then just removing one new line and I don't have so much experience with mail servers nor Ruby, unfortunately.
