### ISSUE TITLE
postal dns check error & postal_worker =>  Exit 1

### ISSUE THREAD

**Issue by zamko00** [postalserver/postal#1965]
Hello i have problem after install on ubuntu 20.04 TLS

Adding the domain is not accepted at all, 

and while sending messages, it remains pending

> root@mail:~# postal status
>       Name                     Command               State    Ports
> -------------------------------------------------------------------
> postal_cron_1       /docker-entrypoint.sh post ...   Up
> postal_requeuer_1   /docker-entrypoint.sh post ...   Up
> postal_smtp_1       /docker-entrypoint.sh post ...   Up
> postal_web_1        /docker-entrypoint.sh post ...   Up
> postal_worker_1     /docker-entrypoint.sh post ...   Exit 1

![Screenshot 2022-04-21 214015](https://user-images.githubusercontent.com/56938522/164539956-a16b8e6f-0612-4479-b39b-3e43a738cc86.png)

**Comment by willpower232** [comment]
You will have to manually check the DNS records on the server with the `dig` or `nslookup` commands to verify how your server sees the records.

You will need to see the logs of the worker to see what the problem is, it usually is something port related but the logs will confirm.

If you need more help, please open a discussion with more information.
