### ISSUE TITLE
domain has misconfigured DNS records

### ISSUE THREAD

**Issue by arunkuttytry** [postalserver/postal#2061]
Hi 

i am try to add new domain all record add but it not verfied, i am try to multiple time it not woking

![Screenshot 2022-07-08 220453](https://user-images.githubusercontent.com/107031529/178033708-9b027012-48d6-4fd9-9992-0d9d01012bf4.png)

**Comment by jazer143** [comment]
check with Mxtoobox.com or any free onlines tools to checkk if can resolve all DNS records you created. Postal will just resolved it using your server DNS. if this is resolvable, maybe try check your server DNS settings.

**Comment by willpower232** [comment]
If you believe you have set the DNS correctly, you might need to change this setting in order to allow your Postal server to verify it.

https://github.com/postalserver/postal/blob/9f0697f194209f5fae5e451ba8fb888413fe37fa/config/postal.defaults.yml#L17

Otherwise please open a discussion with more information about what is not verifying.

**Comment by arunkuttytry** [comment]
All correct sir . Check my dns. And tool also same.. but it not verified
