### ISSUE TITLE
DKIM Validation failing (gmail)

### ISSUE THREAD

**Issue by mrinc** [postalserver/postal#2101]
## Describe the bug

We're seeing a lot of bounces from gmail addresses:  

```
550-5.7.26 Unauthenticated email from example.com is not accepted due to 550-5.7.26 domain's DMARC policy. Please contact the administrator of 550-5.7.26 example.comdomain if this was a legitimate mail. Please visit 550-5.7.26 https://support.google.com/mail/answer/2451690 to learn about the 550 5.7.26 DMARC initiative. be5-.117 - gsmtp
```

## To Reproduce

Normal use of postal

## Expected behaviour

Not being marked as spam

## Screenshots

n/a

## Environment details 

postal 2.1.1

## Additional information/context

After digging around and a bunch of searching, I think I have worked out why.   
DMARC reports the following auth results:  
```
<auth_results>
      <dkim>
        <domain>example.com</domain>
        <result>fail</result>
        <selector>postal</selector>
      </dkim>
      <spf>
        <domain>psrp.example.com</domain>
        <result>pass</result>
      </spf>
    </auth_results>
```  

Now why on earth is the sector incorrect and not using the correct selector `postal-qkvutv`?  
mailgun/office365/createsend all succeed, but postal fails.  
using mailtester.com says no issues.  

It's the hyphen in the dkim definition.  

For some reason google is splitting it, and thus causing the issues.   

For any records that use hyphens in them, a cname is setup for it like `selector1` -> points to `selector1-example-com` for office365.  

So what I wanted to know, is how easy would it be to remove the hyphen altogether from the dkim generation and to re-generate the dkim keys?

This should eliminate this issue for others as well that experience weird failures related to dkim.

**Comment by willpower232** [comment]
are you able to share your (redacted as necessary) DMARC policy?

**Comment by mrinc** [comment]
@willpower232  you can see it here: https://github.com/postalserver/postal/discussions/2102 

The policy is all dandy, no issues with it.
Only gmail is reporting this issue, and seems to not like the hyphen.

For some ref: 
I just created a new txt record `postal._domainkey` with the same data, and gmail emails are received no issues now.

So the hyphen is definitely an issue.

**Comment by catphish** [comment]
Would it be possible to share the DKIM header of the email that was actually sent?

I just tested this and accidentally reproduced the same problem, but the reason was much simpler!

In my case, the domain's DNS configuration was not validated, and as a consequence, Postal fell back to using the default domain name and default DKIM selector (which is hardcoded to `postal`). If your default domain name `Postal.config.dns.return_path` is the same as the domain name you are trying to send from, then the result is going to be what is reported here.

I find it unlikely the gmail is stripping hyphenated DKIM records for two reasons:
1) The spec allows them.
2) Postal has been using them for 10 years and this is the first report of gmail not liking them.
