### ISSUE TITLE
Problem with IP POOLS

### ISSUE THREAD

**Issue by lvaro22** [postalserver/postal#2174]
Good morning, I'm having a problem deleting an ip pool.

When I go to the section "IP POOLS" on the up right side of the screen, and I want to delete an ip pool previously configurated, the next message appears; "IP pool can not be removed because it is still assigned to server/rules", but I have already removed all assigned rules from the servers.

Previouly, doing tests, I removed all servers and organizations, but the error message was still appearing.

For now, I have to remove it from the database to resolve the problem.

Is this a bug, or am I doing something wrong ?

thanks for your attention.

**Comment by catphish** [comment]
I think the error message here is a little misleading. According to the code, there are two things that will prevent an IP pool being deleted:

```
  has_many :ip_addresses, :dependent => :restrict_with_exception
  has_many :servers, :dependent => :restrict_with_exception
```

From your description, I suspect the problem was likely that the pool still contained IP addresses. The error is not clear that IP addresses need to be removed before the pool can be removed, so I will fix that at least.
