### ISSUE TITLE
New docker compose command

### ISSUE THREAD

**Issue by agent-squirrel** [postalserver/postal#2320]
## Describe the bug

docker-compose as a separate binary is now not advised by the Docker official documentation.

The new command is a plugin for docker which is called as follows:
docker compose

The documentation and install script should be updated to reflect this as currently on systems that have the new docker-compose-plugin installed, the install script fails and needs modifying.

Potentially checking for the existence of either docker-compose or the new plugin may be good way to fix this.

## To Reproduce

1. Install docker-compose-plugin.
2. Run the install script

## Expected behaviour

The install script runs

## Environment details 

 - OS: Ubuntu 22.04

**Comment by willpower232** [comment]
Good observation, the docs suggest following the official install instructions which now endorse the plugin approach.

Do you know enough bash to open a PR at the install repository to adapt this line? https://github.com/postalserver/install/blob/ce3ddfa66e18a7509ebec9c7aebf84fcd70675df/bin/postal#L20

**Comment by agent-squirrel** [comment]
Sure thing.

I have submitted a pull request for detection of either compose command and
run the according binary.
The bash may not be the cleanest and could probably be done more succinctly
but it does work.

Cheers

Adam Heathcote - ***@***.*** - 0416363934

**Comment by willpower232** [comment]
Looks great, I don't think there could be much better, I would probably have tried to run the version commands rather than testing them more generically but your way makes more sense.

**Comment by kcalliauw** [comment]
just leaving a small "me too" kinda message here, ran into this today on a fresh Debian 11 installation. 

On the one hand, the docker-compose version from the Debian repositories no longer supports docker-compose syntax version 3.9 which is used by the installer, hence calling for the use of the more up-to-date versions from Docker CE repositories. Here though, docker-compose no longer exists as a separate binary, so in my case I had to temporarily adjust the bash script to use "docker compose" instead of "docker-compose".

**Comment by maietta** [comment]
Debian 11 user here.

Just ran `nano /usr/bin/postal` to edit the command to remove the hyphen between `docker-compose -p postal $@` to `docker compose -p postal $@`
![image](https://user-images.githubusercontent.com/11745020/235181585-9a7ec9e6-d854-48dd-92d0-2267221666e2.png)

Then CTRL-X and when prompted, type 'y" to save.

Now you you should be able to run the commands.
